#!/usr/bin/env node
// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT
//
// Regenerate both typed clients from the ConfigHub server's own spec.
//
// This directory lives in the ConfigHub repository, next to the spec it is generated
// from (public/core/openapi/), so the clients always describe the API of the server
// in the same tree. A server change and the client code that uses it land in one
// commit, and `make api-clients` there runs this after regenerating the spec. On each
// release the directory is copied to github.com/confighub/js-sdk and published; that
// copy has no spec beside it and is not regenerated there.
//
// One spec drives two independent generators (they emit incompatible artifacts and
// share no code):
//   - @confighub/api        openapi-typescript         -> packages/api/src/schema.d.ts
//   - @confighub/rtk-query  @rtk-query/codegen-openapi -> packages/rtk-query/src/confighubApi.gen.ts
// and the server's input-validation constants are copied into @confighub/api.

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const openapiDir = resolve(root, '../core/openapi');
const specFile = resolve(openapiDir, 'openapi.json');
const validationFile = resolve(openapiDir, 'validation.gen.ts');
const validationOut = resolve(root, 'packages/api/src/validation.ts');
const apiTypesOut = resolve(root, 'packages/api/src/schema.d.ts');
const rtkPkg = resolve(root, 'packages/rtk-query');
const rtkOut = resolve(rtkPkg, 'src/confighubApi.gen.ts');

const HEADER = '// Copyright (C) ConfigHub, Inc.\n// SPDX-License-Identifier: MIT\n';

function withHeader(path) {
  const text = readFileSync(path, 'utf8');
  if (!text.startsWith(HEADER)) writeFileSync(path, HEADER + '\n' + text);
}

const spec = JSON.parse(readFileSync(specFile, 'utf8'));
if (!spec.openapi || !spec.paths) {
  throw new Error(`${specFile} does not look like an OpenAPI spec`);
}

// @confighub/api — validation constants, header swapped for this directory's.
const validation = readFileSync(validationFile, 'utf8').replace(/^(\/\/.*\n)+\n?/, '');
writeFileSync(
  validationOut,
  HEADER +
    '//\n// Generated by the ConfigHub server from its own validation rules; copied by\n' +
    '// scripts/generate.mjs. Do not edit.\n\n' +
    validation,
);
console.log(`generate: wrote ${validationOut}`);

// @confighub/api — openapi-typescript types.
execFileSync('npx', ['openapi-typescript', specFile, '-o', apiTypesOut, '--enum'], {
  stdio: 'inherit',
  cwd: root,
});
withHeader(apiTypesOut);

// @confighub/rtk-query — RTK Query codegen (own generator, own base query). Run from
// the package directory so the config's relative paths resolve.
execFileSync('npx', ['@rtk-query/codegen-openapi', 'openapi-config.cjs'], {
  stdio: 'inherit',
  cwd: rtkPkg,
});
withHeader(rtkOut);

console.log('generate: done');
