#!/usr/bin/env node
// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT
//
// Pull the OpenAPI spec at the pinned version and regenerate BOTH typed clients.
//
// The spec is a version-pegged artifact, not a live "latest" endpoint: on every
// `v*.*.*` release the monorepo mirrors `public/` into the public `confighub/sdk`
// repo, which is tagged with the same semver. So the spec for version X lives at
//   https://raw.githubusercontent.com/confighub/sdk/<X>/core/openapi/openapi.json
// and a given SDK build maps to exactly one server version.
//
// One pegged spec drives two independent generators (they emit incompatible
// artifacts and share no code — see docs):
//   - @confighub/api        openapi-typescript      -> packages/api/src/schema.d.ts
//   - @confighub/rtk-query  @rtk-query/codegen-openapi -> packages/rtk-query/src/confighubApi.gen.ts
//
// The pinned version lives in `.spec-version` at the repo root. Bump it, run this,
// review the diffs, and release.
//
// Override the source for local/preview work:
//   SPEC_URL=http://localhost:9090/api/openapi.json npm run sync-spec
//   SPEC_FILE=../confighub/public/core/openapi/openapi.json npm run sync-spec
//
// SPEC_FILE reads a checkout on disk. That is the only way to sync against an
// unreleased server: the pinned URL resolves to a published tag, so a spec that no
// release carries yet has no URL to fetch.

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const specOut = resolve(root, 'openapi.json');
const validationOut = resolve(root, 'packages/api/src/validation.ts');
const apiTypesOut = resolve(root, 'packages/api/src/schema.d.ts');
const rtkPkg = resolve(root, 'packages/rtk-query');

function pinnedVersion() {
  return readFileSync(resolve(root, '.spec-version'), 'utf8').trim();
}

function specUrl() {
  if (process.env.SPEC_URL) return process.env.SPEC_URL;
  const version = pinnedVersion();
  if (!version) throw new Error('.spec-version is empty');
  return `https://raw.githubusercontent.com/confighub/sdk/${version}/core/openapi/openapi.json`;
}

// node's fetch has no file: scheme, so a local checkout is read rather than fetched.
async function readSpec() {
  const file = process.env.SPEC_FILE;
  if (file) {
    const path = resolve(process.cwd(), file);
    console.log(`sync-spec: reading ${path}`);
    return readFileSync(path, 'utf8');
  }
  const url = specUrl();
  console.log(`sync-spec: fetching ${url}`);
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`fetch ${url} failed: ${res.status} ${res.statusText}`);
  }
  return res.text();
}

// The server also generates the input-validation constants (slug, label and
// annotation patterns and lengths) the UI validates forms with. They ride along in
// the same mirror; the older location under rtkqueryclient/ is read until the
// monorepo moves the file up a level.
async function readValidation() {
  const file = process.env.SPEC_FILE;
  if (file) {
    const dir = dirname(resolve(process.cwd(), file));
    for (const candidate of [resolve(dir, 'validation.gen.ts'), resolve(dir, 'rtkqueryclient/validation.gen.ts')]) {
      try {
        return readFileSync(candidate, 'utf8');
      } catch {
        // try the next location
      }
    }
    throw new Error(`no validation.gen.ts next to ${file}`);
  }
  const version = pinnedVersion();
  const base = `https://raw.githubusercontent.com/confighub/sdk/${version}/core/openapi`;
  for (const url of [`${base}/validation.gen.ts`, `${base}/rtkqueryclient/validation.gen.ts`]) {
    const res = await fetch(url);
    if (res.ok) {
      console.log(`sync-spec: fetching ${url}`);
      return res.text();
    }
  }
  throw new Error(`validation.gen.ts not found in confighub/sdk at ${version}`);
}

async function main() {
  const raw = await readSpec();

  // Validate + normalize (stable formatting, trailing newline) so the committed diff
  // is minimal and reviewable.
  const spec = JSON.parse(raw);
  if (!spec.openapi || !spec.paths) {
    throw new Error('fetched document does not look like an OpenAPI spec');
  }
  writeFileSync(specOut, JSON.stringify(spec, null, 2) + '\n');
  console.log(`sync-spec: wrote ${specOut} (openapi ${spec.info?.version ?? '?'})`);

  // @confighub/api — validation constants, header swapped for this repo's.
  const validation = (await readValidation()).replace(/^(\/\/.*\n)+\n?/, '');
  writeFileSync(
    validationOut,
    '// Copyright (C) ConfigHub, Inc.\n// SPDX-License-Identifier: MIT\n//\n' +
      '// Generated by the ConfigHub server from its own validation rules; synced by\n' +
      '// scripts/sync-spec.mjs at the pinned version. Do not edit.\n\n' +
      validation,
  );
  console.log(`sync-spec: wrote ${validationOut}`);

  // @confighub/api — openapi-typescript types.
  console.log('sync-spec: openapi-typescript -> @confighub/api');
  execFileSync('npx', ['openapi-typescript', specOut, '-o', apiTypesOut, '--enum'], {
    stdio: 'inherit',
    cwd: root,
  });

  // @confighub/rtk-query — RTK Query codegen (own generator, own base query). Run from
  // the package dir so the config's relative paths resolve, matching the monorepo.
  console.log('sync-spec: @rtk-query/codegen-openapi -> @confighub/rtk-query');
  execFileSync('npx', ['@rtk-query/codegen-openapi', 'openapi-config.cjs'], {
    stdio: 'inherit',
    cwd: rtkPkg,
  });

  console.log('sync-spec: done. Review the diffs and add a changeset if anything changed.');
}

main().catch((err) => {
  console.error(`sync-spec: ${err.message}`);
  process.exit(1);
});
