// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT
//
// Generated by the ConfigHub server from its own validation rules; synced by
// scripts/sync-spec.mjs at the pinned version. Do not edit.

export const SLUG_PATTERN = /^[A-Za-z0-9]([\-_.A-Za-z0-9]*[A-Za-z0-9])?$/;
export const SLUG_MAX_LENGTH = 128;
export const SLUG_PATTERN_MESSAGE =
  'Must start and end with a letter or number. May contain letters, numbers, hyphens (-), underscores (_), and periods (.)';

export const LABEL_KEY_PATTERN = /^[A-Za-z0-9]([\-_\./A-Za-z0-9]*[A-Za-z0-9])?$/;
export const LABEL_KEY_MAX_LENGTH = 128;
export const LABEL_KEY_PATTERN_MESSAGE =
  'Must start and end with a letter or number. May contain letters, numbers, hyphens (-), underscores (_), periods (.), and forward slashes (/)';

export const LABEL_VALUE_PATTERN = /^[\-_@/#$%&~+=!?.,:;(){}\[\]<>|A-Za-z0-9](([\-_@/#$%&~+=!?.,:;(){}\[\]<>|A-Za-z0-9]| )*[\-_@/#$%&~+=!?.,:;(){}\[\]<>|A-Za-z0-9])?$/;
export const LABEL_VALUE_MAX_LENGTH = 128;
export const LABEL_VALUE_PATTERN_MESSAGE =
  'Must start and end with a printable character (no leading/trailing spaces). Quotes, backslashes, and wildcards are not allowed';

export const ANNOTATION_KEY_PATTERN = /^[A-Za-z0-9]([\-_\./A-Za-z0-9]*[A-Za-z0-9])?$/;
export const ANNOTATION_KEY_MAX_LENGTH = 128;
export const ANNOTATION_KEY_PATTERN_MESSAGE =
  'Must start and end with a letter or number. May contain letters, numbers, hyphens (-), underscores (_), periods (.), and forward slashes (/)';

export const ANNOTATION_VALUE_PATTERN = /^(.|\n)*$/;
export const ANNOTATION_VALUE_MAX_LENGTH = 1024;
export const ANNOTATION_VALUE_PATTERN_MESSAGE =
  'Any content is allowed, including multiline text';

